import { PrismaClient } from "@prisma/client";
import bcrypt from "bcrypt";

const prisma = new PrismaClient();

async function main() {
  console.log("Seeding database...");

  // ─── User (mirrors User.tsx userData) ────────────────────
  const passwordHash = await bcrypt.hash("senha123", 10);

  const user = await prisma.user.upsert({
    where: { email: "contato@empresa.com.br" },
    update: {},
    create: {
      clientNumber: "319233674",
      name: "EMPRESA",
      email: "contato@empresa.com.br",
      passwordHash,
      document: "312.654.123-48",
      documentType: "CPF",
      phone: "+55 (41) 992702020",
      creditBalance: 0,
      language: "pt-BR",
    },
  });

  console.log(`User created: ${user.name} (${user.clientNumber})`);

  // ─── Address ─────────────────────────────────────────────
  const address = await prisma.address.create({
    data: {
      userId: user.id,
      label: "Casa",
      street: "Rua XV de Novembro",
      number: "1200",
      complement: "Apto 301",
      neighborhood: "Centro",
      city: "Curitiba",
      state: "PR",
      zipCode: "80060-000",
      isDefault: true,
    },
  });

  console.log(`Address created: ${address.street}, ${address.number}`);

  // ─── Categories ──────────────────────────────────────────
  const categories = await Promise.all([
    prisma.category.create({
      data: { name: "Coca-cola", slug: "coca-cola", imageUrl: "http://localhost:3001/uploads/categories/coca-cola.png", sortOrder: 1 },
    }),
    prisma.category.create({
      data: { name: "Sabores", slug: "sabores", imageUrl: "http://localhost:3001/uploads/categories/sabores.png", sortOrder: 2 },
    }),
    prisma.category.create({
      data: { name: "Cervejas", slug: "cervejas", imageUrl: "http://localhost:3001/uploads/categories/cervejas.png", sortOrder: 3 },
    }),
    prisma.category.create({
      data: { name: "Cervejas Especiais", slug: "cervejas-especiais", imageUrl: "http://localhost:3001/uploads/categories/cervejas_especiais.png", sortOrder: 4 },
    }),
    prisma.category.create({
      data: { name: "Águas", slug: "aguas", imageUrl: "http://localhost:3001/uploads/categories/aguas.png", sortOrder: 5 },
    }),
    prisma.category.create({
      data: { name: "Sucos", slug: "sucos", imageUrl: "http://localhost:3001/uploads/categories/sucos.png", sortOrder: 6 },
    }),
    prisma.category.create({
      data: { name: "Chás", slug: "chas", imageUrl: "http://localhost:3001/uploads/categories/chas.png", sortOrder: 7 },
    }),
    prisma.category.create({
      data: { name: "Monster", slug: "monster", imageUrl: "http://localhost:3001/uploads/categories/monster.png", sortOrder: 8 },
    }),
    prisma.category.create({
      data: { name: "Bebidas Esportivas", slug: "bebidas-esportivas", imageUrl: "http://localhost:3001/uploads/categories/bebidas_esportivas.png", sortOrder: 9 },
    }),
    prisma.category.create({
      data: { name: "Drinks Prontos", slug: "drinks-prontos", imageUrl: "http://localhost:3001/uploads/categories/drinks_prontos.png", sortOrder: 10 },
    }),
    prisma.category.create({
      data: { name: "Destilados", slug: "destilados", imageUrl: "http://localhost:3001/uploads/categories/destilados.png", sortOrder: 11 },
    }),
    prisma.category.create({
      data: { name: "Vinhos", slug: "vinhos", imageUrl: "http://localhost:3001/uploads/categories/vinhos.png", sortOrder: 12 },
    }),
    prisma.category.create({
      data: { name: "Balas e gomas", slug: "balas-e-gomas", imageUrl: "http://localhost:3001/uploads/categories/balas_e_gomas.png", sortOrder: 13 },
    }),
    prisma.category.create({
      data: { name: "Doces e cereais", slug: "doces-e-cereais", imageUrl: "http://localhost:3001/uploads/categories/doces_e_cereais.png", sortOrder: 14 },
    }),
    prisma.category.create({
      data: { name: "Salgadinhos", slug: "salgadinhos", imageUrl: "http://localhost:3001/uploads/categories/salgadinhos.png", sortOrder: 15 },
    }),
  ]);

  const [
    cocaCola,
    sabores,
    cervejas,
    cervejasEspeciais,
    aguasCategory,
    sucosCategory,
    chasCategory,
    monster,
    bebidasEsportivas,
    drinksProntos,
    destilados,
    vinhos,
    balasEGomas,
    docesECereais,
    salgadinhos
  ] = categories;

  // Compatibility aliases for the existing products defined below
  const refrigerantes = cocaCola;
  const aguas = aguasCategory;
  const sucos = sucosCategory;
  const chas = chasCategory;
  const energeticos = monster;
  const isotonicos = bebidasEsportivas;

  console.log(`Categories created: ${categories.map((c) => c.name).join(", ")}`);

  // ─── Products (bebidas não alcoólicas) ───────────────────
  const products = await Promise.all([
    // Refrigerantes
    prisma.product.create({
    data: {
      categoryId: refrigerantes.id,
      name: "Coca-Cola Original",
      slug: "coca-cola-original-2l-pet-fardo-6",
      description: "Refrigerante Coca-Cola Original 2L embalagem PET. Fardo com 6 unidades.",
      imageUrl: "http://localhost:3001/uploads/products/coca2l.png",
      price: 58.26,
      sku: "CC-ORIG-2L-PET-6",
      unit: "fardo",
      unitCount: 6,
      volume: 2000,
      packageType: "pet",
      stock: 100,
      minStock: 20,
      isActive: true,
      isFeatured: true,
      sortOrder: 1,
      },
    }),
    // 2
    prisma.product.create({
      data: {
        categoryId: refrigerantes.id,
        name: "Coca-Cola Original",
        slug: "coca-cola-original-350ml-lata-fardo-12",
        description: "Refrigerante Coca-Cola Original 350ml Lata. Fardo com 12 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/coca350.png",
        price: 39.60,
        sku: "CC-ORIG-350ML-LATA-12",
        unit: "fardo",
        unitCount: 12,
        volume: 350,
        packageType: "lata",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 2,
      },
    }),
    // 3
    prisma.product.create({
      data: {
        categoryId: refrigerantes.id,
        name: "Coca-Cola Zero Açúcar",
        slug: "coca-cola-zero-acucar-350ml-lata-fardo-6",
        description: "Refrigerante Coca-Cola Zero Açúcar 350ml Lata. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/cocaz350.png",
        price: 19.80,
        sku: "CC-ZERO-350ML-LATA-6",
        unit: "fardo",
        unitCount: 6,
        volume: 350,
        packageType: "lata",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 3,
      },
    }),
    // 4
    prisma.product.create({
      data: {
        categoryId: refrigerantes.id,
        name: "Coca-Cola Zero Açúcar",
        slug: "coca-cola-zero-acucar-2l-pet-fardo-6",
        description: "Refrigerante Coca-Cola Zero Açúcar 2L embalagem PET. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/cocaz2l.png",
        price: 58.26,
        sku: "CC-ZERO-2L-PET-6",
        unit: "fardo",
        unitCount: 6,
        volume: 2000,
        packageType: "pet",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 4,
      },
    }),
    // 5
    prisma.product.create({
      data: {
        categoryId: refrigerantes.id,
        name: "Coca-Cola Original",
        slug: "coca-cola-original-200ml-pet-fardo-12",
        description: "Refrigerante Coca-Cola Original 200ml embalagem PET. Fardo com 12 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/coca200.png",
        price: 19.32,
        sku: "CC-ORIG-200ML-PET-12",
        unit: "fardo",
        unitCount: 12,
        volume: 200,
        packageType: "pet",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 5,
      },
    }),
    // 6
    prisma.product.create({
      data: {
        categoryId: refrigerantes.id,
        name: "Coca-Cola Original",
        slug: "coca-cola-original-220ml-lata-fardo-6",
        description: "Refrigerante Coca-Cola Original 220ml Lata. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/coca220.png",
        price: 12.54,
        sku: "CC-ORIG-220ML-LATA-6",
        unit: "fardo",
        unitCount: 6,
        volume: 220,
        packageType: "lata",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 6,
      },
    }),
    // 7
    prisma.product.create({
      data: {
        categoryId: refrigerantes.id,
        name: "Coca-Cola Original",
        slug: "coca-cola-original-220ml-lata-fardo-12",
        description: "Refrigerante Coca-Cola Original 220ml Lata. Fardo com 12 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/coca220b.png",
        price: 25.08,
        sku: "CC-ORIG-220ML-LATA-12",
        unit: "fardo",
        unitCount: 12,
        volume: 220,
        packageType: "lata",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 7,
      },
    }),
    // 8
    prisma.product.create({
      data: {
        categoryId: refrigerantes.id,
        name: "Coca-Cola Original",
        slug: "coca-cola-original-250ml-garrafa-fardo-12",
        description: "Refrigerante Coca-Cola Original 250ml Garrafa. Fardo com 12 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/coca250.png",
        price: 39.60,
        sku: "CC-ORIG-250ML-GARRAFA-12",
        unit: "fardo",
        unitCount: 12,
        volume: 250,
        packageType: "garrafa",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 8,
      },
    }),
    // 9
    prisma.product.create({
      data: {
        categoryId: refrigerantes.id,
        name: "Coca-Cola Original",
        slug: "coca-cola-original-310ml-lata-fardo-6",
        description: "Refrigerante Coca-Cola Original 310ml Lata. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/coca310.png",
        price: 19.80,
        sku: "CC-ORIG-310ML-LATA-6",
        unit: "fardo",
        unitCount: 6,
        volume: 310,
        packageType: "lata",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 9,
      },
    }),
    // 10
    prisma.product.create({
      data: {
        categoryId: refrigerantes.id,
        name: "Coca-Cola Original",
        slug: "coca-cola-original-600ml-pet-fardo-6",
        description: "Refrigerante Coca-Cola Original 600ml embalagem PET. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/coca600.png",
        price: 25.20,
        sku: "CC-ORIG-600ML-PET-6",
        unit: "fardo",
        unitCount: 6,
        volume: 600,
        packageType: "pet",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 10,
      },
    }),
    // 11
    prisma.product.create({
      data: {
        categoryId: refrigerantes.id,
        name: "Coca-Cola Original",
        slug: "coca-cola-original-1l-pet-fardo-6",
        description: "Refrigerante Coca-Cola Original 1L embalagem PET. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/coca1l.png",
        price: 36.24,
        sku: "CC-ORIG-1L-PET-6",
        unit: "fardo",
        unitCount: 6,
        volume: 1000,
        packageType: "pet",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 11,
      },
    }),
    // 12
    prisma.product.create({
      data: {
        categoryId: refrigerantes.id,
        name: "Coca-Cola Original",
        slug: "coca-cola-original-1-5l-pet-fardo-6",
        description: "Refrigerante Coca-Cola Original 1.5L embalagem PET. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/coca15l.png",
        price: 50.70,
        sku: "CC-ORIG-1-5L-PET-6",
        unit: "fardo",
        unitCount: 6,
        volume: 1500,
        packageType: "pet",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 12,
      },
    }),
    // 13
    prisma.product.create({
      data: {
        categoryId: refrigerantes.id,
        name: "Coca-Cola Original",
        slug: "coca-cola-original-2-5l-pet-fardo-4",
        description: "Refrigerante Coca-Cola Original 2.5L embalagem PET. Fardo com 4 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/coca25l.png",
        price: 46.04,
        sku: "CC-ORIG-2-5L-PET-4",
        unit: "fardo",
        unitCount: 4,
        volume: 2500,
        packageType: "pet",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 13,
      },
    }),
    // 14
    prisma.product.create({
      data: {
        categoryId: refrigerantes.id,
        name: "Coca-Cola Original",
        slug: "coca-cola-original-3l-pet-fardo-3",
        description: "Refrigerante Coca-Cola Original 3L embalagem PET. Fardo com 3 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/coca3l.png",
        price: 50.76,
        sku: "CC-ORIG-3L-PET-3",
        unit: "fardo",
        unitCount: 3,
        volume: 3000,
        packageType: "pet",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 14,
      },
    }),
    // 15
    prisma.product.create({
      data: {
        categoryId: refrigerantes.id,
        name: "Coca-Cola Zero Açúcar",
        slug: "coca-cola-zero-acucar-200ml-pet-fardo-12",
        description: "Refrigerante Coca-Cola Zero Açúcar 200ml embalagem PET. Fardo com 12 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/cocaz200.png",
        price: 19.32,
        sku: "CC-ZERO-200ML-PET-12",
        unit: "fardo",
        unitCount: 12,
        volume: 200,
        packageType: "pet",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 15,
      },
    }),
    // 16
    prisma.product.create({
      data: {
        categoryId: refrigerantes.id,
        name: "Coca-Cola Zero Açúcar",
        slug: "coca-cola-zero-acucar-220ml-lata-fardo-6",
        description: "Refrigerante Coca-Cola Zero Açúcar 220ml Lata. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/cocaz220.png",
        price: 12.54,
        sku: "CC-ZERO-220ML-LATA-6",
        unit: "fardo",
        unitCount: 6,
        volume: 220,
        packageType: "lata",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 16,
      },
    }),
    // 17
    prisma.product.create({
      data: {
        categoryId: refrigerantes.id,
        name: "Coca-Cola Zero Açúcar",
        slug: "coca-cola-zero-acucar-220ml-lata-fardo-12",
        description: "Refrigerante Coca-Cola Zero Açúcar 220ml Lata. Fardo com 12 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/cocaz220b.png",
        price: 25.08,
        sku: "CC-ZERO-220ML-LATA-12",
        unit: "fardo",
        unitCount: 12,
        volume: 220,
        packageType: "lata",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 17,
      },
    }),
    // 18
    prisma.product.create({
      data: {
        categoryId: refrigerantes.id,
        name: "Coca-Cola Zero Açúcar",
        slug: "coca-cola-zero-acucar-250ml-garrafa-fardo-12",
        description: "Refrigerante Coca-Cola Zero Açúcar 250ml Garrafa. Fardo com 12 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/cocaz250.png",
        price: 39.60,
        sku: "CC-ZERO-250ML-GARRAFA-12",
        unit: "fardo",
        unitCount: 12,
        volume: 250,
        packageType: "garrafa",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 18,
      },
    }),
    // 19
    prisma.product.create({
      data: {
        categoryId: refrigerantes.id,
        name: "Coca-Cola Zero Açúcar",
        slug: "coca-cola-zero-acucar-600ml-pet-fardo-6",
        description: "Refrigerante Coca-Cola Zero Açúcar 600ml embalagem PET. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/cocaz600.png",
        price: 25.20,
        sku: "CC-ZERO-600ML-PET-6",
        unit: "fardo",
        unitCount: 6,
        volume: 600,
        packageType: "pet",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 19,
      },
    }),
    // 20
    prisma.product.create({
      data: {
        categoryId: refrigerantes.id,
        name: "Coca-Cola Zero Açúcar",
        slug: "coca-cola-zero-acucar-1l-pet-fardo-6",
        description: "Refrigerante Coca-Cola Zero Açúcar 1L embalagem PET. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/cocaz1l.png",
        price: 36.24,
        sku: "CC-ZERO-1L-PET-6",
        unit: "fardo",
        unitCount: 6,
        volume: 1000,
        packageType: "pet",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 20,
      },
    }),

    // Sabores (28 produtos reais exportados do banco)
    prisma.product.create({
      data: {
        categoryId: sabores.id,
        name: "Fanta Guaraná",
        slug: "fanta-guarana-6280",
        description: "Refrigerante Fanta Guaraná 200ml embalagem PET. Fardo com 12 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781495773986-111070892.png",
        price: 18.00,
        unit: "fardo",
        unitCount: 12,
        volume: 200,
        packageType: "pet",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 21,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: sabores.id,
        name: "Fanta Guaraná",
        slug: "fanta-guarana-1116",
        description: "Refrigerante Fanta Guaraná 220ml Lata. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781495787116-722755673.png",
        price: 11.64,
        unit: "fardo",
        unitCount: 6,
        volume: 220,
        packageType: "lata",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 22,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: sabores.id,
        name: "Fanta Guaraná",
        slug: "fanta-guarana-8867",
        description: "Refrigerante Fanta Guaraná 2L embalagem PET. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781495825778-509072442.png",
        price: 44.70,
        unit: "fardo",
        unitCount: 6,
        volume: 2000,
        packageType: "pet",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 23,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: sabores.id,
        name: "Fanta Guaraná",
        slug: "fanta-guarana-9192",
        description: "Refrigerante Fanta Guaraná 3L embalagem PET. Fardo com 4 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781495840974-262540237.png",
        price: 32.88,
        unit: "fardo",
        unitCount: 4,
        volume: 3000,
        packageType: "pet",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 24,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: sabores.id,
        name: "Fanta Guaraná Zero Açúcar",
        slug: "fanta-guarana-zero-acucar-8330",
        description: "Refrigerante Fanta Guaraná Zero Açúcar 350ml Lata. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781496180718-277211539.png",
        price: 17.10,
        unit: "fardo",
        unitCount: 6,
        volume: 350,
        packageType: "lata",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 25,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: sabores.id,
        name: "Fanta Guaraná Zero Açúcar",
        slug: "fanta-guarana-zero-acucar-5343",
        description: "Refrigerante Fanta Guaraná Zero Açúcar 2L embalagem PET. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781496209644-348545765.png",
        price: 44.70,
        unit: "fardo",
        unitCount: 6,
        volume: 2000,
        packageType: "pet",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 26,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: sabores.id,
        name: "Fanta Laranja",
        slug: "fanta-laranja-8381",
        description: "Refrigerante Fanta Laranja 200ml embalagem PET. Fardo com 12 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781495583919-452435655.png",
        price: 18.00,
        unit: "fardo",
        unitCount: 12,
        volume: 200,
        packageType: "pet",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 27,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: sabores.id,
        name: "Fanta Laranja",
        slug: "fanta-laranja-1107",
        description: "Refrigerante Fanta Laranja 220ml Lata. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781495612321-290695779.png",
        price: 11.64,
        unit: "fardo",
        unitCount: 6,
        volume: 220,
        packageType: "lata",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 28,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: sabores.id,
        name: "Fanta Laranja",
        slug: "fanta-laranja-9205",
        description: "Refrigerante Fanta Laranja 350ml Lata. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781495637451-772051999.png",
        price: 17.46,
        unit: "fardo",
        unitCount: 6,
        volume: 350,
        packageType: "lata",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 29,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: sabores.id,
        name: "Fanta Laranja",
        slug: "fanta-laranja-1753",
        description: "Refrigerante Fanta Laranja 600ml embalagem PET. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781495657104-117552899.png",
        price: 23.70,
        unit: "fardo",
        unitCount: 6,
        volume: 600,
        packageType: "pet",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 30,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: sabores.id,
        name: "Fanta Laranja",
        slug: "fanta-laranja-3855",
        description: "Refrigerante Fanta Laranja 2L embalagem PET. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781495675978-12183.png",
        price: 47.76,
        unit: "fardo",
        unitCount: 6,
        volume: 2000,
        packageType: "pet",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 31,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: sabores.id,
        name: "Fanta Laranja",
        slug: "fanta-laranja-8358",
        description: "Refrigerante Fanta Laranja 3L embalagem PET. Fardo com 4 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781495706583-457964908.png",
        price: 39.28,
        unit: "fardo",
        unitCount: 4,
        volume: 3000,
        packageType: "pet",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 32,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: sabores.id,
        name: "Fanta Laranja Zero Açúcar",
        slug: "fanta-laranja-zero-acucar-4982",
        description: "Refrigerante Fanta Laranja Zero Açúcar 350ml Lata. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781495729319-526105660.png",
        price: 17.46,
        unit: "fardo",
        unitCount: 6,
        volume: 350,
        packageType: "lata",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 33,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: sabores.id,
        name: "Fanta Laranja Zero Açúcar",
        slug: "fanta-laranja-zero-acucar-3571",
        description: "Refrigerante Fanta Laranja Zero Açúcar 2L embalagem PET. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781495750025-425219248.png",
        price: 47.76,
        unit: "fardo",
        unitCount: 6,
        volume: 2000,
        packageType: "pet",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 34,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: sabores.id,
        name: "Fanta Maracujá",
        slug: "fanta-maracuja-2758",
        description: "Refrigerante Fanta Maracujá 350ml Lata. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781496502738-634371984.png",
        price: 17.46,
        unit: "fardo",
        unitCount: 6,
        volume: 350,
        packageType: "lata",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 35,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: sabores.id,
        name: "Fanta Maracujá",
        slug: "fanta-maracuja-7431",
        description: "Refrigerante Fanta Maracujá 2L embalagem PET. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781496526487-640859873.png",
        price: 47.76,
        unit: "fardo",
        unitCount: 6,
        volume: 2000,
        packageType: "pet",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 36,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: sabores.id,
        name: "Fanta Uva",
        slug: "fanta-uva-5855",
        description: "Refrigerante Fanta Uva 200ml embalagem PET. Fardo com 12 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781496401748-525730531.png",
        price: 18.00,
        unit: "fardo",
        unitCount: 12,
        volume: 200,
        packageType: "pet",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 37,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: sabores.id,
        name: "Fanta Uva",
        slug: "fanta-uva-1885",
        description: "Refrigerante Fanta Uva 220ml Lata. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781496417113-925624490.png",
        price: 11.64,
        unit: "fardo",
        unitCount: 6,
        volume: 220,
        packageType: "lata",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 38,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: sabores.id,
        name: "Fanta Uva",
        slug: "fanta-uva-8503",
        description: "Refrigerante Fanta Uva 350ml Lata. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781496432544-734394357.png",
        price: 17.46,
        unit: "fardo",
        unitCount: 6,
        volume: 350,
        packageType: "lata",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 39,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: sabores.id,
        name: "Fanta Uva",
        slug: "fanta-uva-1833",
        description: "Refrigerante Fanta Uva 600ml embalagem PET. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781496458897-485000503.png",
        price: 23.70,
        unit: "fardo",
        unitCount: 6,
        volume: 600,
        packageType: "pet",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 40,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: sabores.id,
        name: "Fanta Uva",
        slug: "fanta-uva-5121",
        description: "Refrigerante Fanta Uva 2L embalagem PET. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781496482016-766331385.png",
        price: 47.76,
        unit: "fardo",
        unitCount: 6,
        volume: 2000,
        packageType: "pet",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 41,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: sabores.id,
        name: "Fanta Xbox Carmesim",
        slug: "fanta-xbox-carmesim-8458",
        description: "Refrigerante Fanta Xbox Carmesim 350ml Lata. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781495560226-941379810.png",
        price: 17.46,
        unit: "fardo",
        unitCount: 6,
        volume: 350,
        packageType: "lata",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 42,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: sabores.id,
        name: "Sprite Original",
        slug: "sprite-original-2951",
        description: "Refrigerante Sprite Original 200ml embalagem PET. Fardo com 12 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781496540736-892050027.png",
        price: 18.00,
        unit: "fardo",
        unitCount: 12,
        volume: 200,
        packageType: "pet",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 43,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: sabores.id,
        name: "Sprite Original",
        slug: "sprite-original-8280",
        description: "Refrigerante Sprite Original 220ml Lata. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781496556181-654587392.png",
        price: 11.64,
        unit: "fardo",
        unitCount: 6,
        volume: 220,
        packageType: "lata",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 44,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: sabores.id,
        name: "Sprite Original",
        slug: "sprite-original-2880",
        description: "Refrigerante Sprite Original 350ml Lata. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781496570207-458028675.png",
        price: 17.46,
        unit: "fardo",
        unitCount: 6,
        volume: 350,
        packageType: "lata",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 45,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: sabores.id,
        name: "Sprite Original",
        slug: "sprite-original-3722",
        description: "Refrigerante Sprite Original 600ml Lata. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781496592107-241705657.png",
        price: 23.70,
        unit: "fardo",
        unitCount: 6,
        volume: 600,
        packageType: "lata",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 46,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: sabores.id,
        name: "Sprite Original",
        slug: "sprite-original-9941",
        description: "Refrigerante Sprite Original 2L embalagem PET. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781496610927-277985948.png",
        price: 47.76,
        unit: "fardo",
        unitCount: 6,
        volume: 2000,
        packageType: "pet",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 47,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: sabores.id,
        name: "Sprite Zero Açúcar",
        slug: "sprite-zero-acucar-9979",
        description: "Refrigerante Sprite Zero Açúcar 2L embalagem PET. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781496637286-775990903.png",
        price: 47.76,
        unit: "fardo",
        unitCount: 6,
        volume: 2000,
        packageType: "pet",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 48,
      },
    }),

    // Cervejas
    prisma.product.create({
      data: {
        categoryId: cervejas.id,
        name: "Kaiser Lager",
        slug: "kaiser-lager-1122",
        description: "Cerveja Kaiser Lager 350ml Lata. Fardo com 12 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781500694073-729303534.png",
        price: 34.68,
        unit: "fardo",
        unitCount: 12,
        volume: 350,
        packageType: "lata",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 49,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: cervejas.id,
        name: "Kaiser Pilsen",
        slug: "kaiser-pilsen-1428",
        description: "Cerveja Kaiser Pilsen 473ml Lata. Fardo com 12 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781500717380-547704239.png",
        price: 43.08,
        unit: "fardo",
        unitCount: 12,
        volume: 473,
        packageType: "lata",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 50,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: cervejas.id,
        name: "Sol Pilsen",
        slug: "sol-pilsen-8374",
        description: "Cerveja Sol Pilsen 330ml Garrafa. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781500765809-537636065.png",
        price: 29.94,
        unit: "fardo",
        unitCount: 6,
        volume: 330,
        packageType: "garrafa",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 51,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: cervejas.id,
        name: "Sol Premium",
        slug: "sol-premium-8309",
        description: "Cerveja Sol Premium 600ml Garrafa. Fardo com 12 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781500783545-973006684.png",
        price: 107.29,
        unit: "fardo",
        unitCount: 12,
        volume: 600,
        packageType: "garrafa",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 52,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: cervejas.id,
        name: "Sol Premium",
        slug: "sol-premium-518",
        description: "Cerveja Sol Premium 350ml Lata. Fardo com 12 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781500799030-847474689.png",
        price: 49.08,
        unit: "fardo",
        unitCount: 12,
        volume: 350,
        packageType: "lata",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 53,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: cervejas.id,
        name: "Sol Premium 0.0%",
        slug: "sol-premium-0-0-7911",
        description: "Cerveja Sol Premium 0.0% 330ml Garrafa. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781500746021-448679907.png",
        price: 29.94,
        unit: "fardo",
        unitCount: 6,
        volume: 330,
        packageType: "garrafa",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 54,
      },
    }),

    // Cervejas Especiais
    prisma.product.create({
      data: {
        categoryId: cervejasEspeciais.id,
        name: "Cerpa Export",
        slug: "cerpa-export-1798",
        description: "Cerveja Cerpa Export 350ml Garrafa. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781500943449-163545555.png",
        price: 32.70,
        unit: "fardo",
        unitCount: 6,
        volume: 350,
        packageType: "garrafa",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 55,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: cervejasEspeciais.id,
        name: "Cerpa Export",
        slug: "cerpa-export-1168",
        description: "Cerveja Cerpa Export 350ml Lata. Fardo com 12 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781500953506-347229525.png",
        price: 60.00,
        unit: "fardo",
        unitCount: 12,
        volume: 350,
        packageType: "lata",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 56,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: cervejasEspeciais.id,
        name: "Therezópolis Sem Glúten",
        slug: "therezopolis-sem-gluten-5425",
        description: "Cerveja Therezópolis Sem Glúten 350ml Lata. Fardo com 12 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781500908448-414403647.png",
        price: 44.16,
        unit: "fardo",
        unitCount: 12,
        volume: 350,
        packageType: "lata",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 57,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: cervejasEspeciais.id,
        name: "Therezópolis Sem Glúten",
        slug: "therezopolis-sem-gluten-5502",
        description: "Cerveja Therezópolis Sem Glúten 355ml Garrafa. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781500927332-161952589.png",
        price: 27.30,
        unit: "fardo",
        unitCount: 6,
        volume: 355,
        packageType: "garrafa",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 58,
      },
    }),

    // Águas
    prisma.product.create({
      data: {
        categoryId: aguas.id,
        name: "Água Crystal Com Gás",
        slug: "agua-crystal-com-gas-2506",
        description: "Água Crystal Com Gás 350ml PET. Fardo com 12 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781501235707-563830250.png",
        price: 25.56,
        unit: "fardo",
        unitCount: 12,
        volume: 350,
        packageType: "pet",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 59,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: aguas.id,
        name: "Água Crystal Com Gás",
        slug: "agua-crystal-com-gas-219",
        description: "Água Crystal Com Gás 1.5L PET. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781501260827-703084038.png",
        price: 18.18,
        unit: "fardo",
        unitCount: 6,
        volume: 1500,
        packageType: "pet",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 60,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: aguas.id,
        name: "Água Crystal Com Gás",
        slug: "agua-crystal-com-gas-8212",
        description: "Água Crystal Com Gás 500ml PET. Fardo com 12 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781501311658-97860045.png",
        price: 20.52,
        unit: "fardo",
        unitCount: 12,
        volume: 500,
        packageType: "pet",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 61,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: aguas.id,
        name: "Água Crystal Sem Gás",
        slug: "agua-crystal-sem-gas-6459",
        description: "Água Crystal Sem Gás 310ml Garrafa. Fardo com 48 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781501129603-713152760.png",
        price: 52.32,
        unit: "fardo",
        unitCount: 48,
        volume: 310,
        packageType: "garrafa",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 62,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: aguas.id,
        name: "Água Crystal Sem Gás",
        slug: "agua-crystal-sem-gas-4745",
        description: "Água Crystal Sem Gás 350ml PET. Fardo com 12 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781501160341-84220055.png",
        price: 25.56,
        unit: "fardo",
        unitCount: 12,
        volume: 350,
        packageType: "pet",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 63,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: aguas.id,
        name: "Água Crystal Sem Gás",
        slug: "agua-crystal-sem-gas-7244",
        description: "Água Crystal Sem Gás 1.5L PET. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781501182686-432057739.png",
        price: 15.84,
        unit: "fardo",
        unitCount: 6,
        volume: 1500,
        packageType: "pet",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 64,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: aguas.id,
        name: "Água Crystal Sem Gás",
        slug: "agua-crystal-sem-gas-6782",
        description: "Água Crystal Sem Gás 1L PET. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781501202498-799863590.png",
        price: 15.60,
        unit: "fardo",
        unitCount: 6,
        volume: 1000,
        packageType: "pet",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 65,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: aguas.id,
        name: "Água Crystal Sem Gás",
        slug: "agua-crystal-sem-gas-1481",
        description: "Água Crystal Sem Gás 5L PET. Fardo com 2 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781501218805-268210548.png",
        price: 16.78,
        unit: "fardo",
        unitCount: 2,
        volume: 5000,
        packageType: "pet",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 66,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: aguas.id,
        name: "Água Crystal Sem Gás",
        slug: "agua-crystal-sem-gas-6947",
        description: "Água Crystal Sem Gás 300ml PET. Fardo com 24 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781501290225-155747362.png",
        price: 27.36,
        unit: "fardo",
        unitCount: 24,
        volume: 300,
        packageType: "pet",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 67,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: aguas.id,
        name: "Água Crystal Sem Gás",
        slug: "agua-crystal-sem-gas-6881",
        description: "Água Crystal Sem Gás 500ml PET. Fardo com 12 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781501331681-673611212.png",
        price: 18.24,
        unit: "fardo",
        unitCount: 12,
        volume: 500,
        packageType: "pet",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 68,
      },
    }),

    // Sucos
    prisma.product.create({
      data: {
        categoryId: sucos.id,
        name: "Del Valle Frut Laranja",
        slug: "del-valle-frut-laranja-7716",
        description: "Suco Del Valle Frut Laranja 450ml PET. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781501668043-325394997.png",
        price: 15.66,
        unit: "fardo",
        unitCount: 6,
        volume: 450,
        packageType: "pet",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 69,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: sucos.id,
        name: "Del Valle Frut Laranja",
        slug: "del-valle-frut-laranja-1303",
        description: "Suco Del Valle Frut Laranja 1L PET. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781501698425-294266875.png",
        price: 21.06,
        unit: "fardo",
        unitCount: 6,
        volume: 1000,
        packageType: "pet",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 70,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: sucos.id,
        name: "Del Valle Frut Uva",
        slug: "del-valle-frut-uva-1045",
        description: "Suco Del Valle Frut Uva 450ml PET. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781501651947-365763866.png",
        price: 15.66,
        unit: "fardo",
        unitCount: 6,
        volume: 450,
        packageType: "pet",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 71,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: sucos.id,
        name: "Del Valle Frut Uva",
        slug: "del-valle-frut-uva-146",
        description: "Suco Del Valle Frut Uva 1L PET. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781501684746-243867476.png",
        price: 21.06,
        unit: "fardo",
        unitCount: 6,
        volume: 1000,
        packageType: "pet",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 72,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: sucos.id,
        name: "Del Valle Limonada Classic",
        slug: "del-valle-limonada-classic-15",
        description: "Suco Del Valle Limonada Classic 290ml Lata. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781501585450-739201633.png",
        price: 18.00,
        unit: "fardo",
        unitCount: 6,
        volume: 290,
        packageType: "lata",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 73,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: sucos.id,
        name: "Del Valle Limonada Pink",
        slug: "del-valle-limonada-pink-3091",
        description: "Suco Del Valle Limonada Pink 290ml Lata. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781501607233-343750107.png",
        price: 18.00,
        unit: "fardo",
        unitCount: 6,
        volume: 290,
        packageType: "lata",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 74,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: sucos.id,
        name: "Del Valle Limonada Tropical",
        slug: "del-valle-limonada-tropical-4466",
        description: "Suco Del Valle Limonada Tropical 290ml Lata. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781501626473-620741789.png",
        price: 18.00,
        unit: "fardo",
        unitCount: 6,
        volume: 290,
        packageType: "lata",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 75,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: sucos.id,
        name: "Del Valle Néctar Manga",
        slug: "del-valle-nectar-manga-7231",
        description: "Suco Del Valle Néctar Manga 290ml Lata. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781501570925-745067852.png",
        price: 18.00,
        unit: "fardo",
        unitCount: 6,
        volume: 290,
        packageType: "lata",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 76,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: sucos.id,
        name: "Del Valle Néctar Maracujá",
        slug: "del-valle-nectar-maracuja-2947",
        description: "Suco Del Valle Néctar Maracujá 290ml Lata. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781501496275-151661662.png",
        price: 18.66,
        unit: "fardo",
        unitCount: 6,
        volume: 290,
        packageType: "lata",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 77,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: sucos.id,
        name: "Del Valle Néctar Pêssego",
        slug: "del-valle-nectar-pessego-2312",
        description: "Suco Del Valle Néctar Pêssego 290ml Lata. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781501516575-325018554.png",
        price: 18.00,
        unit: "fardo",
        unitCount: 6,
        volume: 290,
        packageType: "lata",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 78,
      },
    }),
    prisma.product.create({
      data: {
        categoryId: sucos.id,
        name: "Del Valle Néctar Uva",
        slug: "del-valle-nectar-uva-5374",
        description: "Suco Del Valle Néctar Uva 290ml Lata. Fardo com 6 unidades.",
        imageUrl: "http://localhost:3001/uploads/products/1781501551607-81904231.png",
        price: 18.00,
        unit: "fardo",
        unitCount: 6,
        volume: 290,
        packageType: "lata",
        stock: 100,
        minStock: 20,
        isActive: true,
        isFeatured: false,
        sortOrder: 79,
      },
    }),
  ]);

  console.log(`Products created: ${products.length} items`);

  // ─── Orders (mirrors Order.tsx data) ─────────────────────

  // Order 2: Entregue — R$ 358,40
  const order2 = await prisma.order.create({
    data: {
      orderNumber: "40028921",
      userId: user.id,
      addressId: address.id,
      status: "DELIVERED",
      subtotal: 358.13,
      deliveryFee: 0,
      discount: 0,
      total: 358.13,
      paymentMethod: "CREDIT_CARD",
      createdAt: new Date("2026-01-01T12:42:00"),
      confirmedAt: new Date("2026-01-01T13:00:00"),
      shippedAt: new Date("2026-01-02T08:00:00"),
      deliveredAt: new Date("2026-01-02T10:05:00"),
      orderItems: {
        create: [
          { productId: products.find(p => p.slug === "agua-crystal-sem-gas-6881")!.id, quantity: 15, unitPrice: 18.24, totalPrice: 273.60 }, 
          { productId: products.find(p => p.slug === "agua-crystal-com-gas-2506")!.id, quantity: 2, unitPrice: 25.56, totalPrice: 51.12 },
          { productId: products.find(p => p.slug === "coca-cola-zero-acucar-350ml-lata-fardo-6")!.id, quantity: 1, unitPrice: 19.80, totalPrice: 19.80 },
        ],
      },
    },
  });

  // Order 3: Cancelado — R$ 999,90
  const order3 = await prisma.order.create({
    data: {
      orderNumber: "40028920",
      userId: user.id,
      addressId: address.id,
      status: "CANCELLED",
      subtotal: 1000.88,
      deliveryFee: 0,
      discount: 0,
      total: 1000.88,
      paymentMethod: "BOLETO",
      createdAt: new Date("2026-01-01T12:32:00"),
      cancelledAt: new Date("2026-01-01T13:02:00"),
      orderItems: {
        create: [
          { productId: products.find(p => p.slug === "coca-cola-original-2l-pet-fardo-6")!.id, quantity: 10, unitPrice: 58.26, totalPrice: 582.60 }, 
          { productId: products.find(p => p.slug === "fanta-laranja-3855")!.id, quantity: 5, unitPrice: 47.76, totalPrice: 238.80 },
          { productId: products.find(p => p.slug === "kaiser-lager-1122")!.id, quantity: 5, unitPrice: 34.68, totalPrice: 173.40 },
        ],
      },
    },
  });

  console.log(`Orders created: ${order2.orderNumber}, ${order3.orderNumber}`);

  // ─── Banners (mirrors BannerSlider.tsx) ──────────────────
  await Promise.all([
    prisma.banner.create({
      data: {
        title: "Slide 1",
        imageUrl: "/banners/slide-1.jpg",
        bgColor: "#3b82f6",
        sortOrder: 1,
        isActive: true,
      },
    }),
    prisma.banner.create({
      data: {
        title: "Slide 2",
        imageUrl: "/banners/slide-2.jpg",
        bgColor: "#22c55e",
        sortOrder: 2,
        isActive: true,
      },
    }),
    prisma.banner.create({
      data: {
        title: "Slide 3",
        imageUrl: "/banners/slide-3.jpg",
        bgColor: "#ef4444",
        sortOrder: 3,
        isActive: true,
      },
    }),
  ]);

  console.log("Banners created: 3 slides");

  console.log("Seed completed successfully!");
}

main()
  .catch((e) => {
    console.error("Seed failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
